# Generated by Django 2.1.5 on 2019-04-06 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=20)),
                ('city_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('content_type', models.CharField(max_length=50)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='virtualTravel.City')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=200)),
                ('picture', models.FileField(blank=True, null=True, upload_to='')),
                ('content_type', models.CharField(blank=True, max_length=50)),
                ('gold', models.IntegerField(default=0)),
                ('city_collection', models.ManyToManyField(blank=True, related_name='collected_user', to='virtualTravel.City')),
                ('city_pool', models.ManyToManyField(related_name='unlocked_user', to='virtualTravel.City')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_text', models.CharField(max_length=100)),
                ('quiz_option_1', models.CharField(max_length=50)),
                ('quiz_option_2', models.CharField(max_length=50)),
                ('quiz_option_3', models.CharField(blank=True, max_length=50)),
                ('quiz_option_4', models.CharField(blank=True, max_length=50)),
                ('quiz_answer', models.IntegerField()),
                ('quiz_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='virtualTravel.City')),
                ('quiz_users', models.ManyToManyField(blank=True, to='virtualTravel.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=2000)),
                ('date', models.DateTimeField()),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='virtualTravel.Profile')),
            ],
        ),
    ]
