# Generated by Django 2.1.5 on 2019-04-06 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtualTravel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travel',
            name='current_stop',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='travel',
            name='current_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_travel', to='virtualTravel.Profile'),
        ),
        migrations.AddField(
            model_name='travel',
            name='num_of_stops',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='travel',
            name='made_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_travel', to='virtualTravel.Profile'),
        ),
    ]
