# Generated by Django 2.1.5 on 2019-04-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualTravel', '0006_auto_20190408_0218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='city',
            name='city_description',
        ),
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.CharField(default='No description Added', max_length=1000),
        ),
    ]
