# Generated by Django 2.1.5 on 2019-04-16 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtualTravel', '0007_auto_20190408_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(default='No description Added', max_length=1000)),
                ('picture_url', models.CharField(max_length=500)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='virtualTravel.City')),
            ],
        ),
    ]
