# Generated by Django 2.1.5 on 2019-04-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualTravel', '0009_auto_20190416_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='gold_earned',
            field=models.IntegerField(default=0),
        ),
    ]
