# Generated by Django 2.1.5 on 2019-04-23 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualTravel', '0010_travel_gold_earned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='city',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
