# Generated by Django 2.1.5 on 2019-04-23 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualTravel', '0012_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='city',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
